### ISSUE TITLE
Hash marks in quote constructs incorrectly parsed as comments

### ISSUE THREAD

**Issue by zoffixznet** [MadcapJake/language-perl6fe#10]
As the title says. Here's the example of the image of the parsing issue and below is the actual code:
![hash](https://cloud.githubusercontent.com/assets/5747918/11933081/ab055c6a-a7c7-11e5-9615-61c84c531731.png)

``` perl6
my $irc = IRC::Client.new(
    :host('localhost'),
    :channels<#perl6bot #zofbot>, :testy('mactest'),
    :debug,
    plugins => [
        IRC::Client::Plugin::Debugger.new
    ]
).run;
```

**Comment by MadcapJake** [comment]
This one I'll need some time to figure out a solution to.

**Comment by MadcapJake** [comment]
I've found a quick fix by just moving the quoteword rule.  However if this becomes an issue again, I think I might need to separate out adverbial postcircumfix quotewords to capture this.

If you type:

``` perl6
10 < 100 # but it is > 5
```

The highlighter (unlike the github version) will think that everything within the two angle-brackets is a quoteword construct.  However, I feel that, since these are comments, it's not really terribly likely that someone will have a `>` on the same line as a `<` and if so, you could just spell it out or move it above or below the line.  However, as I said, if this does become a problem, I think we could solve it by creating a special case rule for adverbial postcircumfix quotewords (which I might end up doing anyways as I really am starting to get uncomfortable with the hackishness of the quoteword rule)

**Comment by zoffixznet** [comment]
:+1:
