### ISSUE TITLE
To FE or not to FE?

### ISSUE THREAD

**Issue by ryanerwin** [MadcapJake/language-perl6fe#54]
### Issue Description

> I'm not sure what the difference between `atom-language-perl6` and `atom-language-perl6fe` is. Both seem to have the same 3 contributors. The title on the `atom-language-perl6` Readme.md file makes the matter even more confusing as you write:

> # Atom Perl 6 Support - »ö« (Fun) Edition!

So should people writing Perl 6 install the regular edition or the fun editon? According to Atom's install count, you've got only 475 users of "language-perl6" but 2241 users of "language-perl6fe". Also confusingly, language-perl6's provided language name also seems to be "Perl 6 FE"...

Is one of these the development version and one the stable version?
Is one the current version and the other deprecated?

Please clarify! :-)

**Comment by samcv** [comment]
The new version is language-perl6, I've been working on language-perl6, and due to mass confusion, and somebody's suggestion added "Official Edition" to the other one https://github.com/perl6/atom-language-perl6

`language-perl6` is based on this one but is now an official perl6.org project, under its organization and active work continues there from where it left off in this repo.

**Comment by MadcapJake** [comment]
This package now installs the official package and then disables this one. There is a note in the readme regarding why and a little popup is shown explaining that you installed a deprecated package.  Thanks go to @samcv for cleaning this all up.
